Flight Price Prediction(EDA + Feature Engineering)

In [230]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [231]:
train_df=pd.read_excel('Data_Train.xlsx')
test_df=pd.read_excel('Test_set.xlsx')

In [232]:
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [233]:
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [234]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [235]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2671 entries, 0 to 2670
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          2671 non-null   object
 1   Date_of_Journey  2671 non-null   object
 2   Source           2671 non-null   object
 3   Destination      2671 non-null   object
 4   Route            2671 non-null   object
 5   Dep_Time         2671 non-null   object
 6   Arrival_Time     2671 non-null   object
 7   Duration         2671 non-null   object
 8   Total_Stops      2671 non-null   object
 9   Additional_Info  2671 non-null   object
dtypes: object(10)
memory usage: 208.8+ KB

In [236]:
final_df=pd.concat([train_df,test_df],axis=0)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [237]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
2666,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
2667,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
2668,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
2669,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
2670,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [238]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.7+ MB

In [239]:
final_df['Date_of_Journey'].str.split('/').str[0]

0       24
1        1
2        9
3       12
4       01
        ..
2666     6
2667    27
2668     6
2669     6
2670    15
Name: Date_of_Journey, Length: 13354, dtype: object

In [240]:
# feature engineering process
final_df['Date']=final_df['Date_of_Journey'].str.split('/').str[0]

In [241]:
final_df['Month']=final_df['Date_of_Journey'].str.split('/').str[1]

In [242]:
final_df['Year']=final_df['Date_of_Journey'].str.split('/').str[2]

In [243]:
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,03,2019
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,05,2019
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,06,2019
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,05,2019
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,01,03,2019

In [244]:
final_df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'Date', 'Month', 'Year'],
      dtype='object')

In [245]:
final_df['Date']=final_df['Date'].astype(int)
final_df['Month']=final_df['Month'].astype(int)
final_df['Year']=final_df['Year'].astype(int)

In [246]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
 11  Date             13354 non-null  int64
 12  Month            13354 non-null  int64
 13  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

In [247]:
final_df.drop(columns=['Date_of_Journey'],axis=1,inplace=True)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.9+ MB

In [248]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [249]:
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]

In [250]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [251]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [252]:
final_df['Arrival_Hour']=final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_Minute']=final_df['Arrival_Time'].str.split(':').str[1]

In [253]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_Hour     13354 non-null  object
 14  Arrival_Minute   13354 non-null  object
dtypes: float64(1), int64(3), object(11)
memory usage: 2.1+ MB

In [254]:
final_df['Arrival_Hour']=final_df['Arrival_Hour'].astype(int)
final_df['Arrival_Minute']=final_df['Arrival_Minute'].astype(int)

In [255]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Arrival_Time     13354 non-null  object
 6   Duration         13354 non-null  object
 7   Total_Stops      13353 non-null  object
 8   Additional_Info  13354 non-null  object
 9   Price            10683 non-null  float64
 10  Date             13354 non-null  int64
 11  Month            13354 non-null  int64
 12  Year             13354 non-null  int64
 13  Arrival_Hour     13354 non-null  int64
 14  Arrival_Minute   13354 non-null  int64
dtypes: float64(1), int64(5), object(9)
memory usage: 2.1+ MB

In [256]:
final_df.drop(columns=['Arrival_Time'],axis=1,inplace=True)

In [257]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Duration         13354 non-null  object
 6   Total_Stops      13353 non-null  object
 7   Additional_Info  13354 non-null  object
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int64
 10  Month            13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Arrival_Hour     13354 non-null  int64
 13  Arrival_Minute   13354 non-null  int64
dtypes: float64(1), int64(5), object(8)
memory usage: 2.0+ MB

In [258]:
final_df.head(15)

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882.0,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35
5,SpiceJet,Kolkata,Banglore,CCU → BLR,09:00,2h 25m,non-stop,No info,3873.0,24,6,2019,11,25
6,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,18:55,15h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
7,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:00,21h 5m,1 stop,No info,22270.0,1,3,2019,5,5
8,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,08:55,25h 30m,1 stop,In-flight meal not included,11087.0,12,3,2019,10,25
9,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,11:25,7h 50m,1 stop,No info,8625.0,27,5,2019,19,15
10,Air India,Delhi,Cochin,DEL → BLR → COK,09:45,13h 15m,1 stop,No info,8907.0,1,6,2019,23,0
11,IndiGo,Kolkata,Banglore,CCU → BLR,20:20,2h 35m,non-stop,No info,4174.0,18,4,2019,22,55
12,Air India,Chennai,Kolkata,MAA → CCU,11:40,2h 15m,non-stop,No info,4667.0,24,6,2019,13,55
13,Jet Airways,Kolkata,Banglore,CCU → BOM → BLR,21:10,12h 10m,1 stop,In-flight meal not included,9663.0,9,5,2019,9,20
14,IndiGo,Kolkata,Banglore,CCU → BLR,17:15,2h 35m,non-stop,No info,4804.0,24,4,2019,19,50

In [259]:
final_df['Dept_Hour']=final_df['Dep_Time'].str.split(':').str[0]
final_df['Dept_Minute']=final_df['Dep_Time'].str.split(':').str[1]

In [260]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Dep_Time         13354 non-null  object
 5   Duration         13354 non-null  object
 6   Total_Stops      13353 non-null  object
 7   Additional_Info  13354 non-null  object
 8   Price            10683 non-null  float64
 9   Date             13354 non-null  int64
 10  Month            13354 non-null  int64
 11  Year             13354 non-null  int64
 12  Arrival_Hour     13354 non-null  int64
 13  Arrival_Minute   13354 non-null  int64
 14  Dept_Hour        13354 non-null  object
 15  Dept_Minute      13354 non-null  object
dtypes: float64(1), int64(5), object(10)
memory usage: 2.2+ MB

In [261]:
final_df['Dept_Hour']=final_df['Dept_Hour'].astype(int)
final_df['Dept_Minute']=final_df['Dept_Minute'].astype(int)

In [262]:
final_df.drop(columns=['Dep_Time'],axis=1,inplace=True)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_Hour     13354 non-null  int64
 12  Arrival_Minute   13354 non-null  int64
 13  Dept_Hour        13354 non-null  int64
 14  Dept_Minute      13354 non-null  int64
dtypes: float64(1), int64(7), object(7)
memory usage: 2.1+ MB

In [263]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
Arrival_Hour          0
Arrival_Minute        0
Dept_Hour             0
Dept_Minute           0
dtype: int64

In [264]:
final_df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [265]:
final_df[final_df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dept_Hour,Dept_Minute
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480.0,6,5,2019,9,25,9,45

In [266]:
final_df['Total_Stops']=final_df['Total_Stops'].map({'non-stop':0,'1 stop':1,'2 stops':2,'3 stops':3,'4 stops':4,'nan':1})
final_df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dept_Hour,Dept_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0.0,No info,3897.0,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2.0,No info,7662.0,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2.0,No info,13882.0,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1.0,No info,6218.0,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1.0,No info,13302.0,1,3,2019,21,35,16,50

In [267]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  float64
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int64
 9   Month            13354 non-null  int64
 10  Year             13354 non-null  int64
 11  Arrival_Hour     13354 non-null  int64
 12  Arrival_Minute   13354 non-null  int64
 13  Dept_Hour        13354 non-null  int64
 14  Dept_Minute      13354 non-null  int64
dtypes: float64(2), int64(7), object(6)
memory usage: 2.1+ MB

In [268]:
final_df.drop(columns=['Route'],axis=1,inplace=True)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13354 entries, 0 to 2670
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Duration         13354 non-null  object
 4   Total_Stops      13353 non-null  float64
 5   Additional_Info  13354 non-null  object
 6   Price            10683 non-null  float64
 7   Date             13354 non-null  int64
 8   Month            13354 non-null  int64
 9   Year             13354 non-null  int64
 10  Arrival_Hour     13354 non-null  int64
 11  Arrival_Minute   13354 non-null  int64
 12  Dept_Hour        13354 non-null  int64
 13  Dept_Minute      13354 non-null  int64
dtypes: float64(2), int64(7), object(5)
memory usage: 2.0+ MB

In [269]:
final_df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [270]:
final_df[final_df['Duration']=='5m']
# observations
# duration of flight from mum to hyd cannot be 5 minutes so we have to drop those invalid records

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dept_Hour,Dept_Minute
6474,Air India,Mumbai,Hyderabad,5m,2.0,No info,17327.0,6,3,2019,16,55,16,50
2660,Air India,Mumbai,Hyderabad,5m,2.0,No info,NaN,12,3,2019,16,55,16,50

In [271]:
final_df = final_df[final_df['Duration'] != '5m']
final_df[final_df['Duration']=='5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Arrival_Hour, Arrival_Minute, Dept_Hour, Dept_Minute]
Index: []

In [272]:
# as per me the duration can be calculate by the dept time and arrival time so there is no need of the duration column
# hence dropping it
final_df.drop(columns=['Duration'],axis=1,inplace=True)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13352 entries, 0 to 2670
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  object
 1   Source           13352 non-null  object
 2   Destination      13352 non-null  object
 3   Total_Stops      13351 non-null  float64
 4   Additional_Info  13352 non-null  object
 5   Price            10682 non-null  float64
 6   Date             13352 non-null  int64
 7   Month            13352 non-null  int64
 8   Year             13352 non-null  int64
 9   Arrival_Hour     13352 non-null  int64
 10  Arrival_Minute   13352 non-null  int64
 11  Dept_Hour        13352 non-null  int64
 12  Dept_Minute      13352 non-null  int64
dtypes: float64(2), int64(7), object(4)
memory usage: 1.4+ MB

In [273]:
final_df['Airline'].unique()
# trying label encoding

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [274]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()

In [275]:
final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [276]:
final_df.shape

(13352, 13)

In [277]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dept_Hour,Dept_Minute
0,3,0,5,0.0,8,3897.0,24,3,2019,1,10,22,20
1,1,3,0,2.0,8,7662.0,1,5,2019,13,15,5,50
2,4,2,1,2.0,8,13882.0,9,6,2019,4,25,9,25
3,3,3,0,1.0,8,6218.0,12,5,2019,23,30,18,5
4,3,0,5,1.0,8,13302.0,1,3,2019,21,35,16,50

In [280]:
from sklearn.preprocessing import OneHotEncoder # onehot encoding
ohe=OneHotEncoder(sparse_output=False)
final_df['Airline']=ohe.fit_transform(final_df[['Airline']])
final_df['Source']=ohe.fit_transform(final_df[['Source']])
final_df['Destination']=ohe.fit_transform(final_df[['Destination']])
final_df['Additional_Info']=ohe.fit_transform(final_df[['Additional_Info']])

In [281]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_Hour,Arrival_Minute,Dept_Hour,Dept_Minute
0,0.0,1.0,0.0,0.0,0.0,3897.0,24,3,2019,1,10,22,20
1,0.0,0.0,1.0,2.0,0.0,7662.0,1,5,2019,13,15,5,50
2,0.0,0.0,0.0,2.0,0.0,13882.0,9,6,2019,4,25,9,25
3,0.0,0.0,1.0,1.0,0.0,6218.0,12,5,2019,23,30,18,5
4,0.0,1.0,0.0,1.0,0.0,13302.0,1,3,2019,21,35,16,50